Adds KCS-4
koinos/koinos-contract-standards pull request #12
Opened 2024-06-12 12:03 UTC by sgerbino

Resolves #10.

2024-06-12 13:35 UTC, sgerbino commented
All protocol buffer method arguments should be `_arguments` and all results should be `_result`. Also, we should add each of these standards to https://github.com/koinos/koinos-proto. I propose we put them in `contracts/standard/kcs-*.proto`. I did not completely review all of these refactors, simply normalize them so they can be reviewed individually.

2024-06-12 15:04 UTC, joticajulian approved these changes

2024-06-12 15:37 UTC, mvandeberg commented on KCSs/kcs-4.md
> +   uint64 value = 3 [jstype = JS_STRING];
I thought we were going to add a memo field to the transfer arguments and event.

2024-06-12 15:37 UTC, mvandeberg requested changes
The argument proto types mix use of the `_args` and `_arguments` suffixes.

2024-06-20 17:09 UTC, mvandeberg approved these changes

2024-06-20 17:09 UTC, merged